from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from vector_studio.plugin_interface import Plugin


class WatermarkPlugin(Plugin):
    """Add a text watermark to the bottom-right corner of an SVG."""

    name = "watermark"
    version = "1.0.0"
    description = "Add a text watermark to generated SVGs."
    author = "Bitmap Vector Studio"

    def postprocess(self, svg_path: Path, options: dict[str, Any]) -> Path:
        """Inject a watermark text element into the SVG.

        The watermark text is read from *options* under the key
        ``watermark_text``.  If the key is absent a default text is used.
        """
        text = options.get("watermark_text", "Generated by Bitmap Vector Studio")
        color = options.get("watermark_color", "#999999")
        font_size = options.get("watermark_size", 12)

        content = svg_path.read_text(encoding="utf-8")

        # Determine viewBox width/height to position the watermark.
        viewbox_match = re.search(r'viewBox="([^"]+)"', content)
        if viewbox_match:
            parts = viewbox_match.group(1).split()
            if len(parts) >= 4:
                try:
                    vb_w = float(parts[2])
                    vb_h = float(parts[3])
                except ValueError:
                    vb_w = vb_h = 100
            else:
                vb_w = vb_h = 100
        else:
            # Try width/height attributes
            w_match = re.search(r'width="([^"]+)"', content)
            h_match = re.search(r'height="([^"]+)"', content)
            vb_w = _parse_length(w_match.group(1)) if w_match else 100
            vb_h = _parse_length(h_match.group(1)) if h_match else 100

        x = vb_w - 10
        y = vb_h - 10

        watermark_svg = (
            f'<text x="{x}" y="{y}" '
            f'font-size="{font_size}" fill="{color}" '
            f'text-anchor="end" opacity="0.6">{self._escape_xml(text)}</text>'
        )

        # Insert before the closing </svg> tag.
        if "</svg>" in content:
            content = content.replace("</svg>", f"{watermark_svg}</svg>", 1)
        else:
            content += watermark_svg

        svg_path.write_text(content, encoding="utf-8")
        return svg_path

    @staticmethod
    def _escape_xml(text: str) -> str:
        """Escape XML special characters."""
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )


def _parse_length(value: str) -> float:
    """Parse a length string like '100px' or '100' to a float."""
    value = value.strip()
    for suffix in ("px", "pt", "em", "rem", "%", "ex", "pc", "cm", "mm", "in"):
        if value.lower().endswith(suffix):
            value = value[: -len(suffix)]
            break
    try:
        return float(value)
    except ValueError:
        return 100.0
